# Generated by Django 4.2.4 on 2023-09-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_accountant_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('medicinename', models.CharField(max_length=100)),
                ('companyname', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
