# Generated by Django 4.2.4 on 2023-09-06 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0024_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientfeedback',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.patient'),
        ),
    ]
