# Generated by Django 4.2.4 on 2023-09-06 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0025_patientfeedback_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.doctor'),
        ),
    ]
