# Generated by Django 4.2.5 on 2023-09-14 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0032_prescription_medicinescount'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionMedicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicinename', models.TextField()),
                ('medicinesCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='medicinesCount',
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medicines',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.prescriptionmedicine'),
        ),
    ]
