# Generated by Django 4.2.5 on 2023-09-14 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0033_prescriptionmedicine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptionmedicine',
            name='medicinename',
        ),
        migrations.RemoveField(
            model_name='prescriptionmedicine',
            name='medicinesCount',
        ),
        migrations.AddField(
            model_name='prescriptionmedicine',
            name='medicineCount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medicines',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.prescriptionmedicine'),
        ),
        migrations.AddField(
            model_name='prescriptionmedicine',
            name='medicineName',
            field=models.TextField(null=True),
        ),
    ]
