# Generated by Django 4.2.5 on 2023-09-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0034_remove_prescriptionmedicine_medicinename_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='medicines',
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicine1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicine1Count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicine2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicine2Count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicine3',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicine3Count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicine4',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicine4Count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicine5',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicine5Count',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='PrescriptionMedicine',
        ),
    ]
