# Generated by Django 4.2.5 on 2023-09-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0035_remove_prescription_medicines_prescription_medicine1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='advice',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='extraMedicine',
            field=models.TextField(null=True),
        ),
    ]
