# Generated by Django 4.2.4 on 2023-09-16 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0036_prescription_advice_prescription_extramedicine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='assignedDoctorId',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='symptoms',
        ),
    ]
